template: |
  ## Release Notes
  $CHANGES
  
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

categories:
  - title: 'Breaking'
    label: 'breaking'
  - title: 'New'
    label: 'feature'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Maintenance'
    label: 'maintenance'
  - title: 'Documentation'
    label: 'docs'

include-labels:
  - 'breaking'
  - 'feature'
  - 'bug'
  - 'maintenance'
  - 'docs'
