<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ProjectType>ProgramLibrary</ProjectType>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net8</TargetFramework>
    <Nullable>disable</Nullable>
    <LangVersion>10</LangVersion>
    <RootNamespace>PepperDash.Essentials.Plugins</RootNamespace>
    <Deterministic>false</Deterministic>
    <AssemblyTitle>PepperDash.Essentials.Plugins.Crestron.Nvx</AssemblyTitle>
    <Company>PepperDash Technology</Company>
    <Description>This software is a plugin designed to work as a part of PepperDash Essentials for Crestron control processors. This plugin allows for control Crestron NVX devices.</Description>
    <Copyright>Copyright 2026</Copyright>
    <Version>1.0.0-local</Version>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <InformationalVersion>$(Version)</InformationalVersion>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <Authors>PepperDash Technologies</Authors>
    <AssemblyName>PepperDash.Essentials.Plugins.Crestron.Nvx</AssemblyName>
    <PackageId>PepperDash.Essentials.Plugins.Crestron.Nvx</PackageId>
    <PackageProjectUrl>https://github.com/PepperDash/epi-crestron-nvx</PackageProjectUrl>
    <PackageTags>crestron 4series nvx</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Properties\**" />
    <EmbeddedResource Remove="Properties\**" />
    <None Remove="Properties\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="PepperDashEssentials" Version="3.0.0-dev-v3-routing.63">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>